services:
  - type: web
    name: football-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: data
      mountPath: /opt/render/project/src/db
      sizeGB: 1